version: '3'

services:
  consumer:
    build:
      context: ..
      dockerfile: ./dockers/Dockerfile.consumer
    image: 'rmq-tester-consumer:latest'
    environment:
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD
      - RABBITMQ_QUEUE_NAME
      - RABBITMQ_PREFETCH_COUNT
    restart: 'no'

  producer:
    build:
      context: ..
      dockerfile: ./dockers/Dockerfile.producer
    image: 'rmq-tester-producer:latest'
    environment:
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD
      - RABBITMQ_QUEUE_NAME
    ports:
      - 9000:3000
    restart: 'no'
