version: '3'

services:
  application:
    build:
      args:
        USERNAME: ${USER}
        USER_UID: 1996 # id -u
        USER_GID: 1996 # id -g
    ports:
      - '9234:3000'
    volumes:
      - ~/.gitconfig:/home/${USER}/.gitconfig:ro
      - ~/.bashrc:/home/${USER}/.bashrc:ro
      - ~/.bash_aliases:/home/${USER}/.bash_aliases:ro
      - ~/.bash_profile:/home/${USER}/.bash_profile:ro
      - ~/.inputrc:/home/${USER}/.inputrc:ro
      - ~/.dircolors:/home/${USER}/.dircolors:ro

  rabbitmq:
    image: 'rabbitmq:3.8.8-management'
    container_name: rmq-tester-rabbitmq
    ports:
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: example
      RABBITMQ_DEFAULT_PASS: example
